components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/cache/AuthJwtCache.java
components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/internal/JWTBasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/internal/JWTBasicAuthenticatorServiceComponentDataHolder.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
pom.xml

Resolves wso2/product-is#3316
This PR introduces the authenticator that validate the JWT issued by the resident IdP for the username and password
This authenticator is introduced to support authentication over a backchannel mechanism, without posting user credentials over the user agent. 
Therefore, a JWT received by authenticating via the backend API can be validated over this authenticator in the authentication flow.
The authenticator validates a JWT issued by the resident IdP. If the JWT is valid (JWT signature is valid, JWT is not expired, JWT is not replayed), the subject mentioned in the JWT is picked as the authenticated user

Add JWT based basic authenticator.

---

pom.xml

As the group id of JWT basic authenticator was changed the repository released version was upgraded to a major version (6.0.0). This released the basic authenticator 6.0.0 as well, even without any API changes.
So, now the JWT basic authenticator could depend on basic authenticator versions of 5.0.x and 6.0.x  as basic authenticator 6.0.x also didn't include any API changes.
Therefore the dependent basic authenticator version range was changed to include 6.0.x versions as well.

Update dependency version range of basic authenticator for jwt based basic authenticator.

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

Fixes https://github.com/wso2/product-is/issues/4724.
> - For a non-existing user, a failed login attempt should not represent a User. An example for this scenario would be a user trying to login with a non-existing tenant domain.  
> - Therefore, in a non-existing user login failed scenario, the login failed event published to the analytics, shoud not contain a User object having non-existing credentials.
> - The authentication failed exception thrown for a non-existing user login scenario cannot contain a User object having non-existing user creadentials, as extracting a non-existing user from this exception is incorrect. 
> Use a method signature for the authentication failed exception, which does not include the User, for non-existing user login scenarios.
> N/A

Fix non-existing user logging scenarios

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

All configurtions are to be done in `<IS-HOME>/repository/conf/identity/application-authentication.xml` file in the `AuthenticatorConfigs` under `BasicAuthenticator`.
This PR adds the following capabilities to the basic authenticator;
For the following to take effect the `showAuthFailureReason` should be set to `true` e.i. `<Parameter name="showAuthFailureReason">true</Parameter>` 
- mask the user does not exist error code (17001) with the invalid credentials error code (17002).
Set `maskUserNotExistsErrorCode` to `true`
ex: `<Parameter name="maskUserNotExistsErrorCode">true</Parameter>`
deafult value = false
- Omit error response params
Add the error params to be omitted to `errorParamsToOmit`. Applicable values `errorCode`,`failedUsername`,`remainingAttempts`,`lockedReason`. …

Add ability to mask error response and omit error params

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorDataHolder.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
pom.xml

This PR will add the parameters required to enable the Recaptcha when loading the basic authenticator login page. 
* When redirecting to the login page, the authenticator will check whether the Recaptcha is always enabled for the authentication from the Login Policies. (This additional configuration capability is introduced with the PR,https://github.com/wso2-extensions/identity-governance/pull/335
* If this is enabled, Basic authenticator will get the Recaptcha configs from the captcha-config.properties file.
* Then add the following parameters in the redirect UI.
** &reCaptcha
** &reCaptchaKey
** &reCaptchaAPI
Documents need to be updated with the new config details.
- Unit tests provided
Merge this PR after https://github.com/wso2-extensions/identity-governance/pull/335 and bumping the …

Enable recaptcha always for basic authentication if configured

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
pom.xml

Resolves https://github.com/wso2/product-is/issues/8525
Setting the callback param to the login page in the request so that the user is prompted to login after the password reset.
Added a new param `reason` to the callback URI so that scenario can be passed in the request. In this scenario, the `reason` would be as follows.
```
&reason=ADMIN_FORCED_PASSWORD_RESET_VIA_OTP
```
Improved the unit tests to support new improvement.

Redirect to application login page after offline password reset

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

Fix for the remainingAttempts query parameter not returning issue for the users in the secondary user store.
Maintain the state of the user existence through `userExistThreadLocalProperty` to set the error code to IdentityErrorMsgContext accordingly based on the "user does not exist" and "invalid credentials" cases.
Resolves: wso2/product-is#9583
Related PR: https://github.com/wso2-extensions/identity-governance/pull/436

 Fix for the remainingAttempts query parameter not returning issue

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

Downstream code expects the user store domain to be set in the thread-local. This thread-local usually gets populated during any user store operation
at the user store layer. In the auto-login flow, we do not call any user store operations hence the thread-local will not be set.
As a solution, we set the thread-local explicitly. The value for the user store domain is expected to be set in the cookie.

Set user store domain thread local in auto login flow

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
pom.xml

Bypassing `appendUserTenantToUsername` authenticator parameter to basic authenticator, we can force basic authenticator to construct the username by appending the user tenant domain (in the context) to the username.
```
var onLoginRequest = function(context) {
executeStep(1, { authenticatorParams : {
common : {
'appendUserTenantToUsername' : "true"
}
}
}, {
onSuccess: function (context) {
//
}
});
};
```

Add capability to append the user tenant hint to the username in authenticator.

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

> Improve the code coverage
> Add unit tests for basic authenticator
> https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/93

Add unit test for UserStoreClientException in basic authenticator

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

> Fix showing reCaptcha prompt for tenant users when `isTenantedSessionsEnabled` is true when reCaptcha is always enabled for super tenant.
> Use `getUserTenantDomain` method of `AuthenticationContext` instead of `getTenantDomain` method for selecting the tenant.

Fix invalid tenant selecting for redirecting with reCaptcha options

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponentTestCase.java
pom.xml

Adding secure vault support for reCaptcha `site-key`, `site-secret` or any other captcha property. 
Partially resolves : https://github.com/wso2/product-is/issues/11693

Add secure vault support for recaptcha configs

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
pom.xml

Resolves partially https://github.com/wso2/product-is/issues/10760
Depends on https://github.com/wso2/carbon-identity-framework/pull/3582
This fix is to add backward compatibility support to https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/71

Add backward compatibility to #71

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java

Resolves: [wso2/product-is/issues/12175](https://github.com/wso2/product-is/issues/12175)
>  Currently, there is no proper indication for the user that his account is locked due to reaching the maximum failed login attempts. 
>Introduced a new toml property(**showAuthFailureReasonOnLoginPage**) to show account locked error message on the login page.
>This property is connected with the **showAuthFailureReason** property.
```
[authentication.authenticator.basic.parameters]
showAuthFailureReason = true
showAuthFailureReasonOnLoginPage = true
```
Enabling both properties in the deployment.toml, the account locked error message will be displayed on the login page.
[wso2/identity-apps/pull/2257](https://github.com/wso2/identity-apps/pull/2257) …

Add support to show the Account Locked error message on the login page

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
pom.xml

This PR change, will fix the issue of not showing proper error messages in the UI when not approved users are trying to log in when the 'Add User' workflow operation is engaged.
Resolves: wso2/product-is#12462
After merging https://github.com/wso2/carbon-identity-framework/pull/3759 and upgrading the framework version

Redirect to error page when non-approved users are trying to login

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

Resolves https://github.com/wso2/product-is/issues/12790
**admin forced password reset offline flow**
**Current behaviour**
IS already sends sp query params in the callbackURL param. So sending them again is redundant.
` 
https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?client_id=MY_ACCOUNT&code_challenge=ZC5SGiXr9vBZRWq6l2q72pSdeECMCAuQr1c2b66P7pg&code_challenge_method=S256&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fmyaccount&response_mode=form_post&response_type=code&scope=openid+SYSTEM&tenantDomain=carbon.super&sessionDataKey=4b78f773-0b6e-410e-8897-abdaf8597166&relyingParty=MY_ACCOUNT&type=oidc&sp=My+Account&isSaaSApp=true&username=user1%40xyz.com&tenantdomain=xyz.com&confirmation=KCDOMS&ca …

Remove redundant queryparams from redirect URL in admin forced password reset offline flow

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

Remove `recaptchaKey` and `recaptchaAPI` parameters from the authentication endpoint URL.

Remove captcha parameters from the authentication URL

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

* $subject
* Prevent authenticating users via GET requests. When sending GET requests, client credentials have to be sent as query parameters.
Check the request URL contains user credentials.
*  https://github.com/wso2/identity-apps/pull/2971
** Notes
Please merge [identity apps PR]( https://github.com/wso2/identity-apps/pull/2971) after merging this PR

Check if user credentials are sent as query parameters

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorDataHolder.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponentTestCase.java
pom.xml

**Description**
With the fix, pending user information will be sent to analytics  only if we enable a configuration. Configuration is available system wise as well as tenant wise. **Default value for the config will be true.**
System wise configuration should be disabled in the deployment.toml config as below.
[show_pending_user_information]
enabled = false
Tenant wise configuration should be disabled/ enabled through configuration management feature.
1. Create a resource type as below
```
curl --location --request POST 'https://localhost:9443/api/identity/config-mgt/v1.0/resource-type' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{"name": "basic-authenticator-config", "description": …
```

Handle Pending User Information for Analytics

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

A sample
```
executeStep(2, {
stepOptions: {
forceAuth: 'true'
},
authenticatorParams: {
common: {
'username': context.currentKnownSubject.username + '@carbon.super',
'appendUserTenantToUsername': "true",
'additionalParams': 'theme=guardio-life&action=link'
}
}
}, {
onSuccess: function(context) {
}
});
```
`additionalParams` will be passed to the basic auth login page.

Add support to pass custom params to login page form basic authenticator in adaptive scripts

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
pom.xml

Resolves part of [product-is #13525](https://github.com/wso2/product-is/issues/13525)
Dependent on [identity-governance #598](https://github.com/wso2-extensions/identity-governance/pull/598)
This PR modifies the basic authenticator logic to prompt for reCaptcha based on the system wide configuration introduced by [identity-governance #598](https://github.com/wso2-extensions/identity-governance/pull/598). If the config is enabled, reCaptcha will be required in the SSO login flows of all tenants irrespective of the tenant wise reCaptcha configuration for SSO.

Prompt for reCaptcha in SSO login flows based on the system wide config

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

* Use the original query string when the request is an instance of AuthenticationFrameworkWrapper to get the query string with only the url params.
* Add "=" to the search key to not to consider the values of the query string.
* https://github.com/wso2-enterprise/wso2-iam-internal/issues/223

Use the original query string when the request is an instance of AuthenticationFrameworkWrapper

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

- Currently we have `appendUserTenantToUsername` config to add user tenant domain to the username when email as username is not enabled. We have a requirement to append application tenant domain to the username with a config as well. This PR is to cater that requirement. In this PR we are introducing the `appendAppTenantToUsername` flag to append application tenant domain to email username.

Introduce new config to add application tenant domain to username for SaaS applications

---

components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
pom.xml

Fixes https://github.com/wso2/product-is/issues/15223
Merge after - https://github.com/wso2/carbon-identity-framework/pull/4412
As of now, the tenant domain is retrieved from the PRivileged Carbon Context in the framework side. But this leads to [1], where super tenant domain is retrieved in tenanted sessions. Hence, we are passing the tenant domain from the context to the framework method introduced with [2]
[1] - https://github.com/wso2/product-is/issues/15223
[2] - https://github.com/wso2/carbon-identity-framework/pull/4412
> [Overload getSessionByUserId to pass the tenant domain](https://github.com/wso2/carbon-identity-framework/pull/4412)

Get user sessions with user Id and tenant domain

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java

- In order to publish user entered value for analytic purposes, set the input value to context and pass.
- In the username is an invalid value (user does not exists in the system), update the context with a new parameter so that analytics can publish data based on that value
- https://github.com/wso2/product-is/issues/15327

Set user entered username to context so that data publisher can use that value to publish data

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/attribute/handler/BasicAuthAuthAttributeHandler.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/attribute/handler/BasicAuthAuthAttributeHandlerTest.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/resources/testng.xml
pom.xml

This PR adds the auth attribute handler component related to the basic authenticator. Refer https://github.com/wso2-extensions/identity-governance/pull/651 description to get an idea on how the auth attribute handler works.
The component sends the following attributes as auth attributes for basic authenticator
- `username`
- `password`
The following validations are done when the validate attribute method of this auth attribute handler is called.
- Check if required auth attributes are provided.
- Check if provided required auth attributes are not blank.
Related to: https://github.com/wso2/product-is/issues/15449

Add basicauth auth attribute handler

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java

Currently in the identifier first authenticator for Multi Attribute Login the tenant domain is taken from context. With this, for SaaS applications if a user from another tenant tries to log into an application registered in super tenant (or some other tenant), the user cannot be resolved since the tenant domain in context is not that of the user trying to log in. To fix this, when resolving the user, the user's tenant domain is set using MultitenantUtils.
- Issue https://github.com/wso2/product-is/issues/15423
- Issue https://github.com/wso2/product-is/issues/15422

Get tenant domain from MultitenantUtils in Multi Attribute Login

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java

- Default bahavior of the IDF handler is not validating the user from IDF handler.
- To fill he gaps, we are not validating the user when multi attribute login is enabled.
- From this PR, we are removing the error thrown from the IDF handler after validating the user.
- And we have added a new property to context to track that the user is resolved from the IDF or not ,
-  When multi attribute login is enabled, the user is resolved from the IDF 
-  Set `isUserResolved` as true as a property in context.
- Check this property before resolving the user from relevant other authenticators.
https://github.com/wso2/product-is/issues/16302

Fix the validating user from IDF handler

---

components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java

In Asgardeo, when the ActiveSessionsLimitHandler is configured and when a user logins when the maximum allowed number of sessions are shown, they are redirected to `https://api.asgardeo.io/authenticationendpoint/handle-multiple-sessions.do?<query-params>`. 
The base URL is `api.asgardeo.io` where as in other pages related to login, the base URL is `accounts.asgardeo.io/t/<tenanted_path>`.
This PR fixes the redirect URL to be` https://accounts.asgardeo.io/t/<tenant_domain>/authenticationendpoint/handle-multiple-sessions.do?<query-params>`.
In addition, when the URL is tenant qualified, the tenant domain will be used to retrieve the branding configurations that should be applied for `handle-multiple-session.jsp`. This is similar to the way branding being applied to other pages.

Fix redirect URL in active session limit handler

---

components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java

Previously we kept the KEYSTORE_FILE_EXTENSION as follows. With the https://github.com/wso2/product-is/issues/18466 effort, we need to pass the tenant domain to get the relevent file extension to support backward compatibility. 
`public static final String KEYSTORE_FILE_EXTENSION = ".jks";`
Hence, make `KEYSTORE_FILE_EXTENSION` deprecated and keep the same value

Fix keystore issue.

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java

Use `IsUserResolve` context parameter (which was already introduced for multi attribute login feature[1]) for identify weather the user was already resolved in the IDF authenticator and, based on that context parameter, not going to resolve the user again in the Email OTP & SMSOTP authenticators( similar to [2]).
[1] https://github.com/wso2-extensions/identity-local-auth-basicauth/blob/master/components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java#L557-L558
[2] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L184-L1 …

Set IsUserResolve context parameter in ValidateUsername

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

> $subject
If the `context.getProperty(RESOLVE_CREDENTIALS_FROM_RUNTIME_PARAMS)` is null, when casting to Boolean it will be null. Hence when evaluating the if condition, there is a possibility of NPE.

Handle NPE which can be occurred when processing boolean value in the context

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java

&subject
Fixes: https://github.com/wso2/product-is/issues/21504
This will also fix the flow for other tenants. 
The current implementation of the basic authenticator skips the **preprocessUsername** method, which appends the sub-organization ID to the username. Without this appended ID, the userstore manager cannot locate the user in the correct organization. This causes the authentication status to be set as "FAIL", resulting in an authentication failure.
Move the preprocessUsername method call outside the if-condition.

Append sub-org ID to username when domain validation is disabled

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
pom.xml

This PR prevents processing sensitive data (eg: username, password) sent as query parameters in requests by checking for their availability in the query string part of the request.

[Public] Fix accepting user credentials in query parameters

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginConstant.java

Auto login feature login flows use different names compared in prior product versions. To keep the changes consistent update the auto login flow names.
- https://github.com/wso2/product-is/issues/23119
- https://github.com/wso2/identity-apps/pull/7658

Rename Auto Login Flows

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/PasswordOnboardExecutor.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/PasswordOnboardExecutorTest.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/resources/testng.xml
pom.xml

This PR introduces a registration executor to perform the password validation and enrollment into the profile of the user who is being registered.
Related issue: https://github.com/wso2/product-is/issues/23356
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type …

Add password onboard executor

---

components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java

- https://github.com/wso2/product-is/issues/23391
During the sub-organization login flow, a re-authentication is triggered if Organization SSO is the authenticated IdP in the first step. This forces the authenticators added in the second step to execute as well.
Therefore we are adding a check to see if user is already authenticated in the same browser in SessionLimitHandler.

Check for active sessions in the same browser for SessionLimitHandler

---

components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java

> Currently when a user has already created session in an application with an authenticator in the first step and when that same user tries to login to another application which has the previous authenticator + another authenticator + Active Session Limit Handler in authentication steps, it prompts for session termination UI when the max session limit is set to 1. In this kind of scenarios, new session is not created if we forget about the session limiter. So, if the login attempt is a single sign on attempt, ideally session termination prompt should not be prompted. With this PR, if the login attempt is a single sign on attempt, it will be not considered for active session limit.
Related Issue - https://github.com/wso2/product-is/issues/23391
This is also been addressed with …

Fix prompting active session handler for single sign on logins

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

- $subject
- https://github.com/wso2/product-is/issues/23660
- In the previous url we only had the relative path which is not included the base url. Due to that when we redirecting it will use the api URL as the base path rather than the public url.

build the recovery url from the configuration facade.

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java

In the Identifier First, when the `ValidateUsername` is configured as authenticator config, the user is resolved and the `isUserResolved` flag is correctly set in the authentication context. However, when ValidateUsername is set via an adaptive authentication script parameter, the user is still resolved, but isUserResolved is not set in the context.
This PR ensures that `isUserResolved` is correctly set in the context even when ValidateUsername is enabled through the adaptive authentication script.
Refer:
- https://github.com/wso2/product-is/issues/24154

Set IS_USER_RESOLVED property when ValidateUsername is enabled from adaptive script

---

components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java

- With this change now the user input value will be displayed in the next login step if it's displaying. 
- Currently this is only used in the basic auth step.
- https://github.com/wso2/product-is/issues/23967

Update the username to login identifier value to display as the username.

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java

The password set up page and the password set up successful page contained password reset. With this fix after passing the recovery type as invitation, the portal shows the correct msg as shown below.
- https://github.com/wso2/product-is/issues/25243

Append the recovery type as invite for the ask password OTP login flow

---

components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java

> Adding a warn log to detect authentication failures happened along with mismatched tenant domains.
-

Add warn log to detect authentication failures with mismatched tenant domains
