wso2-extensions/identity-local-auth-basicauth

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Depends on https://github.com/wso2/carbon-identity-framework/pull/203
> Adding changes required for analytics

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Reverting since this require the changes in framework 5.2.0 release branch
> Revert "Adding changes required for analytics"

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Reverts wso2-extensions/identity-local-auth-basicauth#9
> Revert "Revert "Adding changes required for analytics""

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
> Refactor pom.xml

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- pom.xml
Updated PR for #23 which implements https://wso2.org/jira/browse/IDENTITY-5166
> IDENTITY-5166 : Admin forced password reset feature

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
https://wso2.org/jira/browse/IDENTITY-4773
> IDENTITY-4773: Supporting error codes generically for Basic Authenticator

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Purpose of "encodeRedirectURL" method is to append sessionID to URL, if cookies are disabled. This is no longer a good practice. Therefore removing the method usages.
> Removing encodeRedirectURL method

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Improve unit test coverage

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponentTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/resources/testng.xml
- pom.xml
> Refactored test classes to use log-utils instead of mocking the log

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Fixed IDENTITY-6388 IDENTITY-6388

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
Fix Intellij suggestions and PR comments mentioned in https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/39
@pulasthi7 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
> Fix Intellij suggestions

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Fix ReCaptcha issue with secondary user-store users when multiple secondary user-stores are configured
> Resolves https://github.com/wso2/product-is/issues/3310
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Fix ReCaptcha issue with secondary user-store users when multiple secondary user-stores are configured

- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
Applies the parent group id to the JWT based basic authenticator.
> Change JWT based basic authenticator group id.

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- pom.xml
Relates to https://github.com/wso2/carbon-identity-framework/pull/1690
> Add identifier first login

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Fix possibility with tampering username in identifier first login
> Fix possibility with tampering username in identifier first login

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/internal/IdentifierAuthenticatorServiceComponent.java
- pom.xml
** Proposed changes in this pull request**
Fix wso2/product-is#3856
When clicks on the back button, it is not possible to login as a different user.
Introduced intermediate confirmation page for the following scenario.
**Problem**:
There are two applications. (A and B).
Identifier first authenticator and Basic authenticator are configured in application A.
Only Basic authenticator is configured in application B.
User first login to the application B as username X. (Basic Auth)
Then user login to the application A as username Y. (Identifier first login). Since there is an already authenticated basic authentication session, the user will be seamlessly login as X instead of Y.
**Solution**.
No prompt. Seamlessly Identify the next authenticator through the already authenticated session. …
> Fix issues in Identifier first Authenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/internal/JWTBasicAuthenticatorServiceComponent.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
- pom.xml
> Migrate annotation and update version 

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/resources/log4j2.properties
- pom.xml
**Proposed changes in this pull request**
- Remove carbon.logging,commons-logging and log4j dependency.
- Add pax-logging dependency
- Remove maven-scr plugin
- Update dependency
> Migrate log4j2 update. 

- pom.xml
>Fix build failure due to maven-source plugin.
> Fix build failure due to maven-source plugin.

- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
> Introduce new version property for the feature compatible version
> Introduce new version property for the feature compatible version

- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
Resolves: https://github.com/wso2/product-is/issues/7176
> Handle userId becoming null for fresh users

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
Upgrade carbon kernel version and release minor version
> Upgrade carbon kernel version and release minor version

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- pom.xml
Resolves: https://github.com/wso2/product-is/issues/8029
> Add missing package import

- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/internal/ActiveSessionsLimitHandlerServiceComponent.java
> Fix code review comments of #61

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
> Fix for issue https://github.com/wso2/product-is/issues/8117
> https://github.com/wso2/carbon-identity-framework/pull/2882
> Add username preprocessing for basic authenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/util/JwtBasicAuthErrorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/BasicAuthErrorConstants.java
- pom.xml
PR covers
added Error codes for Basic authenticator using the code "BAS-XXXXX"
added Error codes for JwtBasic authenticator using the code "JBA-XXXXX"
Resolves wso2/product-is#8667
> add error code for basic auth and jwt basic

- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
Resolves: https://github.com/wso2/product-is/issues/9396
Resolving user ID from the username (using newly implemented the uniquid functions).
Frontporting: https://github.com/wso2-support/identity-local-auth-basicauth/pull/27
> [Fix] Fix active limit session handler

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
Resolves https://github.com/wso2/product-is/issues/8634
> Implement auto login after password reset

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Setup Resend Comfirmation reCaptcha

- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
> Fix https://github.com/wso2/product-is/issues/9916 & https://github.com/wso2/product-is/issues/10764
Find the step of the subject identifier and get the user Id.  For federated user read from the session user store and for the local user directly read user id from userstore.
> Read user ID from subject identifier

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- pom.xml
> Fix https://github.com/wso2/product-is/issues/10923
Merge after https://github.com/wso2/carbon-identity-framework/pull/3325 and update the framework version
> Handle sign in with different account with restart_flow parameter

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Introduce domain check in autoLoginCookie

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Reverts wso2-extensions/identity-local-auth-basicauth#84
> Revert "Introduce domain check in autoLoginCookie"

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginConstant.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
Handle auto login in the registration flow.
> Handle auto login in the registration flow.

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginConstant.java
> Use domain passed from the ALOR cookie in remove cookie
> Use domain passed from the ALOR cookie in remove cookie method

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Handle failure flow in auto-login in to fallback and prompt the basic authentication
> Handle failure flow in auto-login to fallback and prompt the basic authentication

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginConstant.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Validate ALOR cookie max-age.
> Validate ALOR cookie max age.

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> Resolves wso2/product-is#11160
> Handle usernames with invalid tenant domains

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Related to https://github.com/wso2/product-is/issues/11332
This PR is to convey the message to the end-user if the UserStoreClientException is thrown from the userstore level.
The following configuration is needed for this to work.
```
[authentication.authenticator.basic.parameters]
showAuthFailureReason = true
```
> Handle UserStoreClientException in basic authenticator

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
Part of https://github.com/wso2/product-is/issues/11363
> Get tenant from tenant context

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- pom.xml
This PR resolves the Issue in the multi-attribute login feature for tenant users.
Resolves: wso2/product-is#11590
Related to: wso2/product-is#8899
**How to reproduce:**
1. Enabled multi-attribute login feature in a tenant (foo.com) with email attribute (without enabling the email username (enable_email_domain) property).
2. Create a user (Alex) in the tenant and update the email claim with an email address (test@gmail.com).
3. Log in to myaccount app with test@gmail.com@foo.com.
4. Login failed with the following error message in the UI.
>  Login failed! Please recheck the username and password and try again.
Instead of retrieving the tenant domain from context, use the …
> Fix multi attribute login failed for tenant users

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponentTestCase.java
- pom.xml
Remove power mock to be able to build repo in java 11.
> Remove power mock

- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/cache/AuthJwtCache.java
- pom.xml
Move AuthJwtCache to tenant space.
Related Issue : wso2/product-is#11690
> Move AuthJwtCache to tenant space

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Note @Subject
For Builder - https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/114
> Add null check for username to fix possible NPE

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Related Issues: wso2/product-is#4992
> Enable reCaptcha after max failed login attempts.
> Enable reCaptcha after max failed attempt for Basic Authentication

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/internal/IdentifierAuthenticatorServiceComponent.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorDataHolder.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/internal/BasicAuthenticatorServiceComponent.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
$subject
Fixes wso2/product-is#12437
> Ignore username login if it is not configured when using the multi-attribute login

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Address review comments in old PR https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/116
> Address review comments in old PRs

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
fixes https://github.com/wso2/product-is/issues/11449
> Modify callback url in admin force password reset email otp flow
> Fix bug in admin forced password reset flow

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/BasicAuthErrorConstants.java
For username, throw an exception when  null, empty string or space character is there
For password, throw an exception when the password is empty.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> Check for empty username and password

- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
Resolves https://github.com/wso2/product-is/issues/12805
Earlier IS is not session handler is not sending sp name as a query param in the redirect URL
https://localhost:9443/authenticationendpoint/handle-multiple-sessions.do?promptId=52f39a90-e4b3-407b-b782-c94a62784ccd
This PR will improve the session handler to send the sp name as a query param as shown below
`https://localhost:9443/authenticationendpoint/handle-multiple-sessions.do?promptId=52f39a90-e4b3-407b-b782-c94a62784ccc&sp=pickup-app`
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a …
> Add sp name as a query param to redirect URL

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
> Change the version to 6.3.55-SNAPSHOT
> Change the scm tag
> Change the version to SNAPSHOT

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginUtilities.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
> When the tenanted url/session management is enabled, the autologin related configuration needs to be retrieved from the login tenant to support the SaaS application cases.
Part of https://github.com/wso2/product-is/issues/13053
> Link(s) to product documentation that addresses the …
> Get autologin configuration from login tenant.

- pom.xml
> [6.3.x] Update kernel version

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- pom.xml
> [6.3.x] Update kernel and pax-logging versions

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
Resolves [product-is #13522](https://github.com/wso2/product-is/issues/13522)
> Set authenticated subject identifier in authenticated user

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/internal/IdentifierAuthenticatorServiceComponent.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/BasicAuthErrorConstants.java
- pom.xml
Part of fix https://github.com/wso2/product-is/issues/14154
> Support identifier first to resolve user from organization

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandlerConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
> Renames local authenticator display names.
> fix(constants): rename authenticator displayNames

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
> Bump kernel version

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- pom.xml
dependency changes due to moving org mgt service to org mgt core
After https://github.com/wso2-extensions/identity-organization-management-core/pull/1
> Update dependencies due to moving org mgt service to core

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- pom.xml
Reverts wso2-extensions/identity-local-auth-basicauth#148
> Revert "Update dependencies due to moving org mgt service to core"

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandlerConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
Reverts wso2-extensions/identity-local-auth-basicauth#146
> Revert "fix(constants): rename authenticator displayNames"

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandlerConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
Redo: https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/146
> Re "Revert "fix(constants): rename authenticator displayNames""

- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
Fixed issue: https://github.com/wso2/product-is/issues/11027
> active-sessions-limit-handler is not working without adaptive scripts

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
Bump version to 6.7.0-SNAPSHOT
> Bump version to 6.7.0-SNAPSHOT

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
Set recaptcha params in authentication context properties to be used to get redirect URI for Multi Option Page
- https://github.com/wso2/carbon-identity-framework/pull/4301
> Set recaptcha params to Authentication context properties

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
- Refactoring the pom versions to match with the branch.
> [6.6.x] Refactoring pom Versions

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
Bump POM versions to major version: 7.0.0 for IPK product.
> Bump pom version to major version

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandlerConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
Merge 7.0.x with master for IPK
> Merge 7.0.x branch with master

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Remove unnecessary class variable.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Remove instance variable

- pom.xml
- Update the governance version to the latest[1] in basicauth
[1] https://github.com/wso2-extensions/identity-governance/tree/v1.8.8
> Update governance version in basicauth

- pom.xml
> Update carbon-identity-framework and governance version range

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
> The response from identifier first has the userstore as PRIMARY. This PR resolves the userstore domain from the authenticated user.
> Fix issues with using email otp with identifier first

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- Currently the behavior of the IDF handler is to validate username if the tenant contains associated organization (B2B). However this has altered the previous default behavior of not validating the user in the normal flow.
- Also prompting to resolve the user by setting the "ValidateUsername" doesn't try to resolve the user from secondary user stores.
1. This fix will move the server level "ValidateUsername" authenticator config into the adaptive script parameter, where the server config will get overridden by the adaptive property. The user resolution behavior would be as follows.
```
if skipIdentifierPreProcess == "true":
skipAll;
else:
if emailUserNameValidationEnabled == true:
validateUsername();
if multiAttributeLoginEnabled == true:
resolveUser();
if ValidateUsername(adaptive) == …
```
> Add username validation adaptive config and modify validations

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
Reverts wso2-extensions/identity-local-auth-basicauth#175
> Revert "Add username validation adaptive config and modify validations"

- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
> Add diagnostic logs for BasicAuthenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
> Add diagnostic logs for identifier first

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Remove redirect URI from diagnostic logs

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
Add API based authentication support for BasicAuthenticator
> Add API based authentication support for BasicAuthenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/test/java/org/wso2/carbon/identity/application/authenticator/handler/identifier/IdentifierHandlerTestCase.java
Add API Based Authentication support for the identifier first Authenticator
> Add API Based Authentication support for the identifier first Authenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Fix possible null pointer

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/test/java/org/wso2/carbon/identity/application/authenticator/handler/identifier/IdentifierHandlerTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
> Improve basic authenticator

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/test/java/org/wso2/carbon/identity/application/authenticator/handler/identifier/IdentifierHandlerTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
Modify the authenticators with service modifications
> Modify the authenticators with service modifications

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- pom.xml
Error handling from the basic and identifier handler level
> Error handling from the basic and identifier handler level

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/test/java/org/wso2/carbon/identity/application/authenticator/handler/identifier/IdentifierHandlerTestCase.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
> Add displayName

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandlerConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
> Set i18n key

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Add method comment

- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/jwt/JWTBasicAuthenticatorConstants.java
- pom.xml
Issue: 
- https://github.com/wso2/product-is/issues/18466
Improve to define keystore and truststore type from deployment.toml
> Update keystore extension to PKCS12

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth.jwt/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.basicauth/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.basicauth.server.feature/pom.xml
- pom.xml
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Changing snapshot version for next release version

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginUtilities.java
> Pass the server exception when throwing authentication failure when ALOR cookie signature validation

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginUtilities.java
> Log error for analyze the auto login issue

- .github/workflows/pr-builder.yml
- Codecov.yaml
- pom.xml
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Intergrate Codecov to check the unit test coverage of the Repository

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/util/AutoLoginUtilities.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
> Use new methods for signing and signature validation

- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/internal/ActiveSessionsLimitHandlerServiceComponent.java
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/internal/ActiveSessionsLimitHandlerServiceHolder.java
> $Subject
Fixes - https://github.com/wso2/product-is/issues/23078
> Fix issues with concurrent session based access control for sub org users

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/PasswordOnboardExecutor.java
- pom.xml
Related to https://github.com/wso2/product-is/issues/23346
> Bump framework version

- components/org.wso2.carbon.identity.application.authentication.handler.session/pom.xml
- components/org.wso2.carbon.identity.application.authentication.handler.session/src/main/java/org/wso2/carbon/identity/application/authentication/handler/session/ActiveSessionsLimitHandler.java
- This PR adds support for app native authentication for concurrent session based access control
- https://github.com/wso2/product-is/issues/22979
> Add support for API based authentication for active session limit handler

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
> Add review suggestions

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/UserResolveExecutor.java
- https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/234
This pull request simplifies the `UserResolveExecutor` class by removing redundant processing of the `usernameClaim` variable and directly passing it to the `resolveUser` method.
Key change:
* [`UserResolveExecutor.java`](diffhunk://#diff-5619e4de4e3ec0f49efa05ebb63a3af945330b4e9b53436ffa575881f283e02eL103-R103): Removed the call to `MultitenantUtils.getTenantAwareUsername`, which was used to extract the tenant-aware username from `usernameClaim`. The `usernameClaim` is now passed directly to the `resolveUser` method, reducing unnecessary processing.
> Remove resolving tenantAwareUsername

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
- Set the proper error message for USER_EMAIL_NOT_VERIFIED_ERROR_CODE
- https://github.com/wso2/carbon-identity-framework/pull/6938
> Handle USER_EMAIL_NOT_VERIFIED_ERROR_CODE

- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/UserResolveExecutor.java
- components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/test/java/org/wso2/carbon/identity/application/authenticator/handler/identifier/UserResolveExecutorTestCase.java
- pom.xml
- https://github.com/wso2/product-is/issues/24782
This pull request enhances the `UserResolveExecutor` class by introducing support for excluding specific user stores during user resolution and updates its associated test cases to reflect the new functionality. Additionally, it updates the Carbon Identity Framework dependency version.
* Added support for excluding user stores during user resolution using the `FLOW_EXECUTION_USER_STORE_DOMAIN` property. This includes changes to retrieve a list of excluded user stores and skip them during the resolution process (`UserResolveExecutor.java`). [[1]](diffhunk://#diff-5619e4de4e3ec0f49efa05ebb63a3af945330b4e9b53436ffa575881f283e02eR61) [[2]](diffhunk://#diff-5619e4de4e3ec0f49efa05ebb63a3af945330b4e9b53436ffa575881f283e02eL205-L227)
* Modified …
> Fix user store domain resolution in user resolve executor

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
$subject
- https://github.com/wso2/product-is/issues/24790
> Handle ASK password OTP failures and redirect to password reset page

- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.basicauth/src/test/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticatorTestCase.java
- pom.xml
$subject
- https://github.com/wso2/product-is/issues/25504
- https://github.com/wso2/carbon-identity-framework/pull/7289
> Handle email OTP based verification pending scenario with separate error code
